name: Build and Publish

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install PDM
      run: pip install pdm

    - name: Cache PDM packages
      uses: actions/cache@v3
      with:
        path: ~/.pdm/cache
        key: ${{ runner.os }}-pdm-${{ hashFiles('**/pdm.lock') }}
        restore-keys: |
          ${{ runner.os }}-pdm-

    # - name: Verify pyproject.toml location
    #   run: |
    #     if [ ! -f pyproject.toml ]; then
    #       echo "pyproject.toml not found in the root directory
    #       exit 1
    #     fi

    # - name: Regenerate pdm.lock
    #   run: pdm lock

    - name: Install dependencies
      run: pdm install

    - name: Build the project
      run: |
        echo "Current directory: $(pwd)"
        echo "Listing contents:"
        ls -la
        pdm build

    - name: Verify the wheel
      run: pdm info

    - name: Upload distribution to GitHub Packages
      if: github.event_name == 'push'
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/*.whl
